AR = ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar']
ARCH_ST = ['-arch']
ARFLAGS = ['rcs']
BINDIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/bin'
BIN_PERL = ['/usr/bin/perl']
CC = ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'clang'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('9', '1', '0')
CFLAGS = ['-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator11.3.sdk', '-arch', 'x86_64', '-mtvos-version-min=11.2', '-fembed-bitcode', '-I/Users/corey/dev/tvOSMediaPlayer/contrib/FFmpeg-tvOS/thin/x86_64/include', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wno-logical-op-parentheses', '-fcolor-diagnostics', '-Wno-tautological-compare', '-Wno-tautological-constant-out-of-range-compare', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_compiler = ['-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla']
CFLAGS_cshlib = ['-fPIC']
CFLAGS_libav_any = ['-pthread', '-pthread', '-pthread']
CFLAGS_libavcodec = ['-pthread', '-pthread']
CFLAGS_libavdevice = ['-pthread', '-pthread', '-pthread']
CFLAGS_pthreads = ['-pthread']
COMPILER_CC = 'clang'
CONFDIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/etc/mpv'
CONFLOADDIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/etc/mpv'
CPPPATH_ST = '-I%s'
CXXFLAGS_libav_any = ['-pthread', '-pthread', '-pthread']
CXXFLAGS_libavcodec = ['-pthread', '-pthread']
CXXFLAGS_libavdevice = ['-pthread', '-pthread', '-pthread']
DATADIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/share'
DEFINES = []
DEFINES_ST = '-D%s'
DEFINE_COMMENTS = {'HAVE_VDPAU': '', 'HAVE_ICONV': '', 'HAVE_SHADERC_SHARED': '', 'HAVE_VAPOURSYNTH_CORE': '', 'HAVE_VDPAU_GL_X11': '', 'HAVE_LIBM': '', 'HAVE_GLOB_WIN32': '', 'HAVE_LIBBLURAY': '', 'HAVE_MACOS_COCOA_CB': '', 'HAVE_PULSE': '', 'HAVE_LIBASS': '', 'HAVE_WIN32_PIPES': '', 'HAVE_LCMS2': '', 'HAVE_VT_H': '', 'HAVE_VAAPI': '', 'HAVE_WIN32_EXECUTABLE': '', 'HAVE_APPLE_REMOTE': '', 'HAVE_RPI': '', 'HAVE_JAVASCRIPT': '', 'HAVE_CDDA': '', 'MPV_CONFDIR': '', 'HAVE_WASAPI': '', 'HAVE_DIRECT3D': '', 'HAVE_LIBAV_ANY': '', 'HAVE_VIDEOTOOLBOX_GL': '', 'HAVE_DOS_PATHS': '', 'HAVE_DVDNAV': '', 'HAVE_JACK': '', 'HAVE_LIBRT': '', 'HAVE_GL_WIN32': '', 'HAVE_PLAIN_GL': '', 'HAVE_PDF_BUILD': '', 'HAVE_CLANG_DATABASE': '', 'HAVE_ASM': '', 'HAVE_GBM_H': '', 'HAVE_GL_COCOA': '', 'HAVE_LIBARCHIVE': '', 'HAVE_BSD_THREAD_NAME': '', 'HAVE_GLOB': '', 'HAVE_DEBUG_BUILD': '', 'HAVE_CROSSC': '', 'HAVE_ZLIB': '', 'HAVE_DRM': '', 'HAVE_UWP': '', 'HAVE_LIBV4L2': '', 'HAVE_RSOUND': '', 'HAVE_LIBAVDEVICE': '', 'HAVE_LIBMPV_SHARED': '', 'HAVE_WIN32_INTERNAL_PTHREADS': '', 'HAVE_SHADERC_STATIC': '', 'HAVE_LIBAV': '', 'HAVE_WIN32_DESKTOP': '', 'HAVE_LIBAF': '', 'HAVE_SNDIO': '', 'HAVE_VAPOURSYNTH': '', 'HAVE_GNUC': '', 'HAVE_NOEXECSTACK': '', 'HAVE_TV': '', 'HAVE_LIBASS_OSD': '', 'HAVE_TV_V4L2': '', 'HAVE_STDATOMIC': '', 'HAVE_CPLUGINS': '', 'HAVE_OPENSLES': '', 'HAVE_UCHARDET': '', 'HAVE_JPEG': '', 'HAVE_EGL_X11': '', 'HAVE_GLIBC_THREAD_NAME': '', 'HAVE_XV': '', 'HAVE_GL': '', 'HAVE_IOS_GL': '', 'HAVE_ANDROID': '', 'HAVE_VULKAN': '', 'HAVE_GLOB_POSIX': '', 'HAVE_WAYLAND_SCANNER': '', 'HAVE_VAAPI_X11': '', 'HAVE_AUDIOUNIT': '', 'HAVE_FFMPEG': '', 'HAVE_WAYLAND': '', 'HAVE_EGL_DRM': '', 'HAVE_DVDREAD': '', 'HAVE_VAAPI_DRM': '', 'HAVE_POSIX_SPAWN_NATIVE': '', 'HAVE_MACOS_TOUCHBAR': '', 'HAVE_STATIC_BUILD': '', 'CONFIGURATION': '', 'HAVE_GL_DXINTEROP': '', 'HAVE_COREAUDIO': '', 'HAVE_ATOMICS': '', 'HAVE_DVDREAD_COMMON': '', 'HAVE_COCOA': '', 'HAVE_ZSH_COMP': '', 'HAVE_DVBIN': '', 'HAVE_LUA': '', 'HAVE_POSIX_OR_MINGW': '', 'HAVE_VAAPI_WAYLAND': '', 'HAVE_AUDIO_INPUT': '', 'HAVE_VAAPI_GLX': '', 'HAVE_LGPL': '', 'HAVE_GPL': '', 'HAVE_EGL_ANGLE_LIB': '', 'HAVE_VIDEOTOOLBOX_HWACCEL': '', 'HAVE_BSD_FSTATFS': '', 'HAVE_GL_X11': '', 'HAVE_POSIX': '', 'HAVE_BUILD_DATE': '', 'HAVE_VAPOURSYNTH_LAZY': '', 'HAVE_CUDA_HWACCEL': '', 'HAVE_TEST': '', 'HAVE_D3D_HWACCEL': '', 'HAVE_VAAPI_EGL': '', 'HAVE_LIBAVCODEC': '', 'HAVE_LIBDL': '', 'HAVE_EGL_HELPERS': '', 'HAVE_SYS_VIDEOIO_H': '', 'HAVE_CPLAYER': '', 'HAVE_HTML_BUILD': '', 'HAVE_OPENAL': '', 'HAVE_SHADERC': '', 'HAVE_FCHMOD': '', 'HAVE_LIBSMBCLIENT': '', 'HAVE_LINUX_FSTATFS': '', 'HAVE_OPTIMIZE': '', 'HAVE_VAAPI_X_EGL': '', 'HAVE_PTHREADS': '', 'HAVE_RUBBERBAND': '', 'HAVE_POSIX_SPAWN_ANDROID': '', 'HAVE_ENCODING': '', 'HAVE_GL_WAYLAND': '', 'HAVE_OSX_THREAD_NAME': '', 'HAVE_EGL_ANGLE': '', 'DEFAULT_DVD_DEVICE': '', 'HAVE_OSS_AUDIO': '', 'HAVE_DRMPRIME': '', 'HAVE_D3D11': '', 'FULLCONFIG': '', 'DEFAULT_CDROM_DEVICE': '', 'HAVE_WAYLAND_PROTOCOLS': '', 'HAVE_EGL_ANGLE_WIN32': '', 'HAVE_ALSA': '', 'HAVE_MANPAGE_BUILD': '', 'HAVE_LIBMPV_STATIC': '', 'HAVE_CACA': '', 'HAVE_DUMMY_OSD': '', 'HAVE_MINGW': '', 'HAVE_GL_DXINTEROP_D3D9': '', 'HAVE_GBM': '', 'HAVE_POSIX_SPAWN': '', 'HAVE_X11': '', 'HAVE_VIDEODEV': '', 'HAVE_SDL2': '', 'HAVE_D3D9_HWACCEL': '', 'HAVE_MALI_FBDEV': ''}
DEST_BINFMT = 'mac-o'
DEST_CPU = 'x86_64'
DEST_OS = 'darwin'
DOCDIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/share/doc/mpv'
FRAMEWORKPATH_ST = '-F%s'
FRAMEWORK_ST = ['-framework']
FRAMEWORK_audiounit = ['Foundation', 'AudioToolbox']
FRAMEWORK_libav_any = ['AudioToolbox', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo']
FRAMEWORK_libavcodec = ['AudioToolbox', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo']
FRAMEWORK_libavdevice = ['AudioToolbox', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo']
HAVE_AUDIOUNIT = 1
HAVE_BSD_FSTATFS = 1
HAVE_CPLUGINS = 1
HAVE_CUDA_HWACCEL = 1
HAVE_DRMPRIME = 1
HAVE_FCHMOD = 1
HAVE_FFMPEG = 1
HAVE_GLOB_POSIX = 1
HAVE_GNUC = 1
HAVE_ICONV = 1
HAVE_IOS_GL = 1
HAVE_LIBAVCODEC = 1
HAVE_LIBAVDEVICE = 1
HAVE_LIBAV_ANY = 1
HAVE_LIBDL = 1
HAVE_LIBM = 1
HAVE_OSX_THREAD_NAME = 1
HAVE_POSIX = 1
HAVE_PTHREADS = 1
HAVE_STDATOMIC = 1
HAVE_ZLIB = 1
HTMLDIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/share/doc/mpv'
INCDIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/include'
INCLUDES_libav_any = ['/Users/corey/dev/tvOSMediaPlayer/contrib/FFmpeg-tvOS/thin/x86_64/include']
INCLUDES_libavcodec = ['/Users/corey/dev/tvOSMediaPlayer/contrib/FFmpeg-tvOS/thin/x86_64/include']
INCLUDES_libavdevice = ['/Users/corey/dev/tvOSMediaPlayer/contrib/FFmpeg-tvOS/thin/x86_64/include']
LDFLAGS = ['-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator11.3.sdk', '-arch', 'x86_64', '-Wl,-tvos_version_min,11.2', '-lbz2', '-L/Users/corey/dev/tvOSMediaPlayer/contrib/FFmpeg-tvOS/thin/x86_64/lib']
LIBDIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/lib'
LIBPATH_ST = '-L%s'
LIBPATH_libav_any = ['/Users/corey/dev/tvOSMediaPlayer/contrib/FFmpeg-tvOS/thin/x86_64/lib']
LIBPATH_libavcodec = ['/Users/corey/dev/tvOSMediaPlayer/contrib/FFmpeg-tvOS/thin/x86_64/lib']
LIBPATH_libavdevice = ['/Users/corey/dev/tvOSMediaPlayer/contrib/FFmpeg-tvOS/thin/x86_64/lib']
LIB_ST = '-l%s'
LIB_iconv = ['iconv']
LIB_libav_any = ['avfilter', 'm', 'avresample', 'm', 'swscale', 'm', 'postproc', 'm', 'avformat', 'm', 'bz2', 'z', 'avcodec', 'iconv', 'm', 'z', 'swresample', 'm', 'avutil', 'm']
LIB_libavcodec = ['avcodec', 'iconv', 'm', 'z', 'swresample', 'm', 'avutil', 'm']
LIB_libavdevice = ['avdevice', 'm', 'avfilter', 'm', 'avresample', 'm', 'swscale', 'm', 'postproc', 'm', 'avformat', 'm', 'bz2', 'z', 'avcodec', 'iconv', 'm', 'z', 'swresample', 'm', 'avutil', 'm']
LIB_libm = ['m']
LIB_zlib = ['z']
LINKFLAGS = ['-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift_static/macosx', '-Xlinker', '-force_load_swift_libs', '-lc++', '-rdynamic']
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cplugins = ['-rdynamic']
LINKFLAGS_cshlib = ['-dynamiclib']
LINKFLAGS_cstlib = []
LINKFLAGS_libav_any = ['-pthread', '-Wl,-framework,CoreFoundation', '-Wl,-framework,Security', '-pthread', '-pthread']
LINKFLAGS_libavcodec = ['-pthread', '-pthread']
LINKFLAGS_libavdevice = ['-pthread', '-Wl,-framework,CoreFoundation', '-Wl,-framework,Security', '-pthread', '-pthread']
LINK_CC = ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc']
MACOS_SDK = '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk'
MANDIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/share/man'
PKG_CONFIG = ['/usr/local/bin/pkg-config']
PREFIX = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64'
RPATH_ST = '-Wl,-rpath,%s'
SHLIB_MARKER = []
SONAME_ST = []
STLIBPATH_ST = '-L%s'
STLIB_MARKER = []
STLIB_ST = '-l%s'
SWIFT = '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift'
SWIFT_FLAGS = '-frontend -c -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -enable-objc-interop -emit-objc-header -parse-as-library -target x86_64-apple-macosx10.10 -swift-version 3 -O'
ZSHDIR = '/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/thin/x86_64/share/zsh/site-functions'
cfg_files = ['/Users/corey/dev/tvOSMediaPlayer/contrib/mpv-tvOS/scratch/x86_64/config.h']
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.dylib'
cstlib_PATTERN = 'lib%s.a'
define_key = []
known_deps = ['egl-angle-lib', 'cuda-hwaccel', 'dvdread', 'win32-internal-pthreads', 'libaf', 'jpeg', 'wasapi', 'libav', 'egl-drm', 'audiounit', 'posix-spawn', 'iconv', 'lgpl', 'libv4l2', 'librt', 'lua', 'vt.h', 'videotoolbox-hwaccel', 'opensles', 'posix-or-mingw', 'egl-helpers', 'wayland', 'fchmod', 'pdf-build', 'dos-paths', 'coreaudio', 'libm', 'bsd-thread-name', 'uwp', 'libbluray', 'sndio', 'jack', 'libass-osd', 'vaapi-drm', 'ffmpeg', 'libav-any', 'gbm', 'wayland-protocols', 'zsh-comp', 'manpage-build', 'x11', 'vaapi-glx', 'libavcodec', 'atomics', 'pulse', 'glob-win32', 'uchardet', 'gl-dxinterop', 'vapoursynth-core', 'gl', 'dvdread-common', 'static-build', 'cdda', 'gbm.h', 'rsound', 'posix-spawn-native', 'vaapi', 'macos-cocoa-cb', 'javascript', 'bsd-fstatfs', 'vapoursynth', 'pthreads', 'libmpv-static', 'sys_videoio_h', 'vdpau-gl-x11', 'optimize', 'asm', 'win32-executable', 'sdl2', 'libarchive', 'tv', 'drm', 'gl-cocoa', 'gl-x11', 'libass', 'libmpv-shared', 'lcms2', 'encoding', 'cocoa', 'mingw', 'shaderc-shared', 'osx-thread-name', 'rpi', 'direct3d', 'xv', 'clang-database', 'gpl', 'glob-posix', 'vulkan', 'libsmbclient', 'win32-pipes', 'dvbin', 'plain-gl', 'videodev', 'apple-remote', 'd3d9-hwaccel', 'dummy-osd', 'gnuc', 'gl-win32', 'drmprime', 'gl-wayland', 'mali-fbdev', 'caca', 'glibc-thread-name', 'videotoolbox-gl', 'vapoursynth-lazy', 'posix-spawn-android', 'vdpau', 'debug-build', 'zlib', 'posix', 'd3d11', 'libavdevice', 'dvdnav', 'linux-fstatfs', 'stdatomic', 'gl-dxinterop-d3d9', 'egl-angle', 'vaapi-x11', 'ios-gl', 'wayland-scanner', 'html-build', 'vaapi-x-egl', 'egl-x11', 'noexecstack', 'crossc', 'test', 'android', 'vaapi-wayland', 'alsa', 'tv-v4l2', 'vaapi-egl', 'libdl', 'rubberband', 'glob', 'cplayer', 'd3d-hwaccel', 'macos-touchbar', 'openal', 'shaderc-static', 'cplugins', 'win32-desktop', 'build-date', 'os-darwin', 'audio-input', 'shaderc', 'egl-angle-win32', 'oss-audio']
macbundle_PATTERN = '%s.bundle'
satisfied_deps = ['cuda-hwaccel', 'encoding', 'libavcodec', 'libaf', 'atomics', 'osx-thread-name', 'gl', 'audiounit', 'ios-gl', 'gpl', 'iconv', 'bsd-fstatfs', 'videotoolbox-hwaccel', 'posix-or-mingw', 'plain-gl', 'dummy-osd', 'fchmod', 'drmprime', 'gnuc', 'libm', 'libdl', 'glob', 'pthreads', 'glob-posix', 'libmpv-static', 'libavdevice', 'cplugins', 'build-date', 'optimize', 'asm', 'os-darwin', 'libav-any', 'ffmpeg', 'debug-build', 'zlib', 'stdatomic', 'posix']
